### ISSUE TITLE
Which Python versions are supported?

### ISSUE THREAD

**Issue by sedenka** [xMGZx/xdialog#7]
Hi, do you support Python 3.8?
Xdialog 1.0.8 gives me the following error on Python 3.8.10:
```
(venv38) D:\Test>python
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import xdialog
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Test\venv38\lib\site-packages\xdialog\__init__.py", line 42, in <module>
    dialogs = get_dialogs()
  File "D:\Test\venv38\lib\site-packages\xdialog\__init__.py", line 21, in get_dialogs
    from . import windows_dialogs
  File "D:\Test\venv38\lib\site-packages\xdialog\windows_dialogs.py", line 5, in <module>
    from .windows_structs import *
  File "D:\Test\venv38\lib\site-packages\xdialog\windows_structs.py", line 45, in <module>
    class GUID(ctypes.Structure):
  File "D:\Test\venv38\lib\site-packages\xdialog\windows_structs.py", line 53, in GUID
    def __init__(self, data1: int, data2: int, data3: int, data4: tuple[int], *args, **kwargs):
TypeError: 'type' object is not subscriptable
```

**Comment by mathgeniuszach** [comment]
Huh, I thought type annotation brackets came before 3.8, apparently I don't support it...? Should be a simple fix

**Comment by mathgeniuszach** [comment]
Fixed by https://github.com/xMGZx/xdialog/commit/16cd9ce0121a65fd2e920d0df8563c32d35b1310
